# Generated by Django 3.2.7 on 2021-09-25 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='post_img')),
                ('link_video_receita', models.URLField()),
                ('modo_preparo', models.TextField()),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], max_length=1)),
                ('categoria_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receita.categoria')),
            ],
        ),
    ]
