# Generated by Django 3.2.7 on 2021-10-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='dificuldade',
            field=models.CharField(choices=[('I', 'Iniciante'), ('T', 'Intermediario'), ('A', 'Avancado')], max_length=1),
        ),
    ]
