# Generated by Django 3.2.7 on 2021-10-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_auto_20211004_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(default='1.'),
        ),
    ]
