# Generated by Django 3.2.7 on 2021-10-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_alter_receita_nome_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=50),
        ),
    ]
