# Generated by Django 3.2.7 on 2021-10-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_alter_receita_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='epoca',
            field=models.CharField(choices=[('H', 'Halloween'), ('N', 'Natal'), ('P', 'Pascoa'), ('A', 'Dia dos Namorados'), ('C', 'Comum'), ('J', 'Festa Junina')], default='C', max_length=1),
        ),
    ]
