# Generated by Django 3.2.7 on 2021-10-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0004_receita_epoca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_epoca', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='receita',
            name='epoca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receita.epoca'),
        ),
    ]
